Initial RTD hook implementation
allegro-actions/rtd-hook pull request #3
Opened 2021-10-15 12:34 UTC by deejay1

Initial implementation of the RTD hook for automatic doc builds.

2021-10-18 19:33 UTC, bgalek reviewed
a lot of fuss just to make a HTTP request ;) 
didn't see any ts features used, beside that i found only some side-stuff ;)

2021-10-18 19:33 UTC, bgalek commented on .github/workflows/ci.yml
> +          unset GITHUB_REF
why unset GITHUB_REF?

2021-10-18 19:33 UTC, bgalek commented on .gitignore
> +bower_components
lol?:)

2021-10-18 19:33 UTC, bgalek commented on src/main.ts
> +core.setSecret('rtdToken')
looks like debug left

2021-10-18 19:33 UTC, bgalek commented on src/main.ts
> +  const branch = github.context.ref.replace('refs/heads/', '')
this code depends on dispatched event (pr/push) support both or fail for PR ;)

2021-10-18 19:34 UTC, bgalek requested changes

2021-10-18 19:34 UTC, bgalek commented on src/main.ts
> +  run(branch)
await missing, youre not waiting for your promise to complete, and not doing anything after (.then())

2021-10-18 19:39 UTC, deejay1 commented on .gitignore
> +bower_components
stock ;)

2021-10-18 19:43 UTC, bgalek commented on .github/workflows/ci.yml
> +          unset GITHUB_REF
yes, this would be better than like, unseting stuff :D

2021-10-18 19:43 UTC, bgalek commented on .gitignore
> +bower_components
looks like not used code :D

2021-10-18 19:44 UTC, bgalek commented on src/main.ts
> +  run(branch)
seems like bug to me, are you sure that your code will wait for the execution before turning down the container?

2021-10-18 19:45 UTC, bgalek commented on src/main.ts
> +  run(branch)
can you share this github action sample in ts? :) I've seen some that commit node_modules :)

2021-10-18 19:46 UTC, bgalek commented on src/main.ts
> +core.setSecret('rtdToken')
any docs on that? never heard of this, I've assumed that github masks logs by values...

2021-10-19 06:47 UTC, deejay1 commented on src/main.ts
> +  const branch = github.context.ref.replace('refs/heads/', '')
this is gone completely now

2021-10-19 06:47 UTC, deejay1 commented on src/main.ts
> +core.setSecret('rtdToken')
https://github.com/actions/toolkit/tree/main/packages/core#setting-a-secret

2021-10-19 11:42 UTC, bgalek commented on .gitignore
> +.serverless/
a lot of unused rules ;) vupress, next ,nuxt etc. :P

2021-10-19 11:42 UTC, bgalek commented on src/notifier.ts
> +  const branch = github.context.ref.replace('refs/heads/', '')
```
const branch = process.env['GITHUB_HEAD_REF'] || process.env['GITHUB_REF'].slice('refs/heads/'.length);
```
would remove the context dependency, also would work for PR event

2021-10-19 11:42 UTC, bgalek commented on src/notifier.ts
> +  const hookUrl = core.getInput('hookUrl')
you should assert if the input is falsy

2021-10-19 11:42 UTC, bgalek commented on src/notifier.ts
> +  const rtdToken = core.getInput('rtdToken')
you should assert if the input is falsy

2021-10-19 11:42 UTC, bgalek commented on src/notifier.ts
> +  if (resp.result) {
if rtd returns 200 with null body it will fail? is it ok or not?

2021-10-19 11:42 UTC, bgalek commented on action.yml
> +    description: Token for
token for what? :)

2021-10-19 12:29 UTC, deejay1 commented on src/notifier.ts
> +  const branch = github.context.ref.replace('refs/heads/', '')
well I need to push the branch into rtd so I need it's name

2021-10-19 16:53 UTC, deejay1 commented on src/notifier.ts
> +  const rtdToken = core.getInput('rtdToken')
added `{required: true}` which does the same ;)

2021-10-19 16:55 UTC, deejay1 commented on .gitignore
> +.serverless/
cleaned up a bit more

2021-10-20 06:31 UTC, deejay1 commented on src/notifier.ts
> +  const hookUrl = core.getInput('hookUrl')
used `{required: true}`

2021-10-20 06:32 UTC, adowsky approved these changes

2021-10-20 06:47 UTC, bgalek commented on src/main.ts
> +  run(branch)
await will block till end of the execution

2021-10-20 08:20 UTC, merged